export const buttonPrimaryStyle = {
  fontFamily: 'text',
  color: 'button',
  bg: 'azure',
  borderRadius: '4px',
  cursor: 'pointer',
  textDecoration: 'none',
  py: '8px',
  px: '16px',
  '&:hover': {},
  '&:visited': {},
  '&:focus': {},
}

export const buttonSecondaryStyle = {
  userSelect: 'none',
  fontFamily: 'text',
  textAlign: 'center',
  color: 'text',
  bg: 'transparent',
  border: '1px solid',
  borderColor: 'metal',
  borderRadius: '4px',
  cursor: 'pointer',
  textDecoration: 'none',
  py: '8px',
  px: '16px',
  '&:hover': {},
  '&:visited': {},
  '&:focus': {},
}
