/**
 *
 *  Common fields are present in all models
 *
 */

import { WheelroomFields } from '@wheelroom/wheelroom'
import { ShortTextField } from '@wheelroom/wheelroom'

export const configCommonFields: WheelroomFields = {
  __typename: {
    system: true,
    type: 'shortText',
  } as ShortTextField,
  title: {
    helpText:
      'Wordt alleen binnen Contentful gebruikt, verschijnt nooit op de site zelf',
    initialContent: '%Component name% generated by boilerplate',
    name: 'Titel binnen Contentful',
    required: true,
    type: 'shortText',
  } as ShortTextField,
}
