/**
 *
 *  Common fields are present in all models
 *
 */

import { WheelroomFields, ShortTextField } from '@wheelroom/wheelroom'

export const commonFields: WheelroomFields = {
  __typename: {
    system: true,
    type: 'shortText',
  } as ShortTextField,
  title: {
    initialContent: '%Component name% generated by boilerplate',
    required: true,
    translations: {
      name: {
        'en-US': 'Title within Contentful',
        nl: 'Titel binnen Contentful',
      },
      helpText: {
        'en-US':
          'Only used within Contentful, does not appear on the site itself',
        nl:
          'Alleen gebruikt in Contentful, wordt nooit getoond op de site zelf',
      },
    },
    type: 'shortText',
  } as ShortTextField,
}
