import {
  SvgActivity,
  SvgAirplay,
  SvgAlertCircle,
  SvgAlertOctagon,
  SvgAlertTriangle,
  SvgAlignCenter,
  SvgAlignJustify,
  SvgAlignLeft,
  SvgAlignRight,
  SvgAnchor,
  SvgAperture,
  SvgArchive,
  SvgArrowDown,
  SvgArrowDownCircle,
  SvgArrowDownLeft,
  SvgArrowDownRight,
  SvgArrowLeft,
  SvgArrowLeftCircle,
  SvgArrowRight,
  SvgArrowRightCircle,
  SvgArrowUp,
  SvgArrowUpCircle,
  SvgArrowUpLeft,
  SvgArrowUpRight,
  SvgAtSign,
  SvgAward,
  SvgBarChart,
  SvgBarChart2,
  SvgBattery,
  SvgBatteryCharging,
  SvgBell,
  SvgBellOff,
  SvgBluetooth,
  SvgBold,
  SvgBook,
  SvgBookOpen,
  SvgBookmark,
  SvgBox,
  SvgBriefcase,
  SvgCalendar,
  SvgCamera,
  SvgCameraOff,
  SvgCast,
  SvgCheck,
  SvgCheckCircle,
  SvgCheckSquare,
  SvgChevronDown,
  SvgChevronLeft,
  SvgChevronRight,
  SvgChevronUp,
  SvgChevronsDown,
  SvgChevronsLeft,
  SvgChevronsRight,
  SvgChevronsUp,
  SvgChrome,
  SvgCircle,
  SvgClipboard,
  SvgClock,
  SvgCloud,
  SvgCloudDrizzle,
  SvgCloudLightning,
  SvgCloudOff,
  SvgCloudRain,
  SvgCloudSnow,
  SvgCode,
  SvgCodepen,
  SvgCodesandbox,
  SvgCoffee,
  SvgColumns,
  SvgCommand,
  SvgCompass,
  SvgCopy,
  SvgCornerDownLeft,
  SvgCornerDownRight,
  SvgCornerLeftDown,
  SvgCornerLeftUp,
  SvgCornerRightDown,
  SvgCornerRightUp,
  SvgCornerUpLeft,
  SvgCornerUpRight,
  SvgCpu,
  SvgCreditCard,
  SvgCrop,
  SvgCrosshair,
  SvgDatabase,
  SvgDelete,
  SvgDisc,
  SvgDollarSign,
  SvgDownload,
  SvgDownloadCloud,
  SvgDroplet,
  SvgEdit,
  SvgEdit2,
  SvgEdit3,
  SvgExternalLink,
  SvgEye,
  SvgEyeOff,
  SvgFacebook,
  SvgFastForward,
  SvgFeather,
  SvgFigma,
  SvgFile,
  SvgFileMinus,
  SvgFilePlus,
  SvgFileText,
  SvgFilm,
  SvgFilter,
  SvgFlag,
  SvgFolder,
  SvgFolderMinus,
  SvgFolderPlus,
  SvgFramer,
  SvgFrown,
  SvgGift,
  SvgGitBranch,
  SvgGitCommit,
  SvgGitMerge,
  SvgGitPullRequest,
  SvgGithub,
  SvgGitlab,
  SvgGlobe,
  SvgGrid,
  SvgHardDrive,
  SvgHash,
  SvgHeadphones,
  SvgHeart,
  SvgHelpCircle,
  SvgHexagon,
  SvgHome,
  SvgImage,
  SvgInbox,
  SvgInfo,
  SvgInstagram,
  SvgItalic,
  SvgKey,
  SvgLayers,
  SvgLayout,
  SvgLifeBuoy,
  SvgLink,
  SvgLink2,
  SvgLinkedin,
  SvgList,
  SvgLoader,
  SvgLock,
  SvgLogIn,
  SvgLogOut,
  SvgMail,
  SvgMap,
  SvgMapPin,
  SvgMaximize,
  SvgMaximize2,
  SvgMeh,
  SvgMenu,
  SvgMessageCircle,
  SvgMessageSquare,
  SvgMic,
  SvgMicOff,
  SvgMinimize,
  SvgMinimize2,
  SvgMinus,
  SvgMinusCircle,
  SvgMinusSquare,
  SvgMonitor,
  SvgMoon,
  SvgMoreHorizontal,
  SvgMoreVertical,
  SvgMousePointer,
  SvgMove,
  SvgMusic,
  SvgNavigation,
  SvgNavigation2,
  SvgOctagon,
  SvgPackage,
  SvgPaperclip,
  SvgPause,
  SvgPauseCircle,
  SvgPenTool,
  SvgPercent,
  SvgPhone,
  SvgPhoneCall,
  SvgPhoneForwarded,
  SvgPhoneIncoming,
  SvgPhoneMissed,
  SvgPhoneOff,
  SvgPhoneOutgoing,
  SvgPieChart,
  SvgPlay,
  SvgPlayCircle,
  SvgPlus,
  SvgPlusCircle,
  SvgPlusSquare,
  SvgPocket,
  SvgPower,
  SvgPrinter,
  SvgRadio,
  SvgRefreshCcw,
  SvgRefreshCw,
  SvgRepeat,
  SvgRewind,
  SvgRotateCcw,
  SvgRotateCw,
  SvgRss,
  SvgSave,
  SvgScissors,
  SvgSearch,
  SvgSend,
  SvgServer,
  SvgSettings,
  SvgShare,
  SvgShare2,
  SvgShield,
  SvgShieldOff,
  SvgShoppingBag,
  SvgShoppingCart,
  SvgShuffle,
  SvgSidebar,
  SvgSkipBack,
  SvgSkipForward,
  SvgSlack,
  SvgSlash,
  SvgSliders,
  SvgSmartphone,
  SvgSmile,
  SvgSpeaker,
  SvgSquare,
  SvgStar,
  SvgStopCircle,
  SvgSun,
  SvgSunrise,
  SvgSunset,
  SvgTablet,
  SvgTag,
  SvgTarget,
  SvgTerminal,
  SvgThermometer,
  SvgThumbsDown,
  SvgThumbsUp,
  SvgToggleLeft,
  SvgToggleRight,
  SvgTool,
  SvgTrash,
  SvgTrash2,
  SvgTrello,
  SvgTrendingDown,
  SvgTrendingUp,
  SvgTriangle,
  SvgTruck,
  SvgTv,
  SvgTwitch,
  SvgTwitter,
  SvgType,
  SvgUmbrella,
  SvgUnderline,
  SvgUnlock,
  SvgUpload,
  SvgUploadCloud,
  SvgUser,
  SvgUserCheck,
  SvgUserMinus,
  SvgUserPlus,
  SvgUserX,
  SvgUsers,
  SvgVideo,
  SvgVideoOff,
  SvgVoicemail,
  SvgVolume,
  SvgVolume1,
  SvgVolume2,
  SvgVolumeX,
  SvgWatch,
  SvgWifi,
  SvgWifiOff,
  SvgWind,
  SvgX,
  SvgXCircle,
  SvgXOctagon,
  SvgXSquare,
  SvgYoutube,
  SvgZap,
  SvgZapOff,
  SvgZoomIn,
  SvgZoomOut,
} from './index'

export const IconMap: any = {
  activity: SvgActivity,
  airplay: SvgAirplay,
  'alert-circle': SvgAlertCircle,
  'alert-octagon': SvgAlertOctagon,
  'alert-triangle': SvgAlertTriangle,
  'align-center': SvgAlignCenter,
  'align-justify': SvgAlignJustify,
  'align-left': SvgAlignLeft,
  'align-right': SvgAlignRight,
  anchor: SvgAnchor,
  aperture: SvgAperture,
  archive: SvgArchive,
  'arrow-down-circle': SvgArrowDownCircle,
  'arrow-down-left': SvgArrowDownLeft,
  'arrow-down-right': SvgArrowDownRight,
  'arrow-down': SvgArrowDown,
  'arrow-left-circle': SvgArrowLeftCircle,
  'arrow-left': SvgArrowLeft,
  'arrow-right-circle': SvgArrowRightCircle,
  'arrow-right': SvgArrowRight,
  'arrow-up-circle': SvgArrowUpCircle,
  'arrow-up-left': SvgArrowUpLeft,
  'arrow-up-right': SvgArrowUpRight,
  'arrow-up': SvgArrowUp,
  'at-sign': SvgAtSign,
  award: SvgAward,
  'bar-chart-2': SvgBarChart2,
  'bar-chart': SvgBarChart,
  'battery-charging': SvgBatteryCharging,
  battery: SvgBattery,
  'bell-off': SvgBellOff,
  bell: SvgBell,
  bluetooth: SvgBluetooth,
  bold: SvgBold,
  'book-open': SvgBookOpen,
  book: SvgBook,
  bookmark: SvgBookmark,
  box: SvgBox,
  briefcase: SvgBriefcase,
  calendar: SvgCalendar,
  'camera-off': SvgCameraOff,
  camera: SvgCamera,
  cast: SvgCast,
  'check-circle': SvgCheckCircle,
  'check-square': SvgCheckSquare,
  check: SvgCheck,
  'chevron-down': SvgChevronDown,
  'chevron-left': SvgChevronLeft,
  'chevron-right': SvgChevronRight,
  'chevron-up': SvgChevronUp,
  'chevrons-down': SvgChevronsDown,
  'chevrons-left': SvgChevronsLeft,
  'chevrons-right': SvgChevronsRight,
  'chevrons-up': SvgChevronsUp,
  chrome: SvgChrome,
  circle: SvgCircle,
  clipboard: SvgClipboard,
  clock: SvgClock,
  'cloud-drizzle': SvgCloudDrizzle,
  'cloud-lightning': SvgCloudLightning,
  'cloud-off': SvgCloudOff,
  'cloud-rain': SvgCloudRain,
  'cloud-snow': SvgCloudSnow,
  cloud: SvgCloud,
  code: SvgCode,
  codepen: SvgCodepen,
  codesandbox: SvgCodesandbox,
  coffee: SvgCoffee,
  columns: SvgColumns,
  command: SvgCommand,
  compass: SvgCompass,
  copy: SvgCopy,
  'corner-down-left': SvgCornerDownLeft,
  'corner-down-right': SvgCornerDownRight,
  'corner-left-down': SvgCornerLeftDown,
  'corner-left-up': SvgCornerLeftUp,
  'corner-right-down': SvgCornerRightDown,
  'corner-right-up': SvgCornerRightUp,
  'corner-up-left': SvgCornerUpLeft,
  'corner-up-right': SvgCornerUpRight,
  cpu: SvgCpu,
  'credit-card': SvgCreditCard,
  crop: SvgCrop,
  crosshair: SvgCrosshair,
  database: SvgDatabase,
  delete: SvgDelete,
  disc: SvgDisc,
  'dollar-sign': SvgDollarSign,
  'download-cloud': SvgDownloadCloud,
  download: SvgDownload,
  droplet: SvgDroplet,
  'edit-2': SvgEdit2,
  'edit-3': SvgEdit3,
  edit: SvgEdit,
  'external-link': SvgExternalLink,
  'eye-off': SvgEyeOff,
  eye: SvgEye,
  facebook: SvgFacebook,
  'fast-forward': SvgFastForward,
  feather: SvgFeather,
  figma: SvgFigma,
  'file-minus': SvgFileMinus,
  'file-plus': SvgFilePlus,
  'file-text': SvgFileText,
  file: SvgFile,
  film: SvgFilm,
  filter: SvgFilter,
  flag: SvgFlag,
  'folder-minus': SvgFolderMinus,
  'folder-plus': SvgFolderPlus,
  folder: SvgFolder,
  framer: SvgFramer,
  frown: SvgFrown,
  gift: SvgGift,
  'git-branch': SvgGitBranch,
  'git-commit': SvgGitCommit,
  'git-merge': SvgGitMerge,
  'git-pull-request': SvgGitPullRequest,
  github: SvgGithub,
  gitlab: SvgGitlab,
  globe: SvgGlobe,
  grid: SvgGrid,
  'hard-drive': SvgHardDrive,
  hash: SvgHash,
  headphones: SvgHeadphones,
  heart: SvgHeart,
  'help-circle': SvgHelpCircle,
  hexagon: SvgHexagon,
  home: SvgHome,
  image: SvgImage,
  inbox: SvgInbox,
  info: SvgInfo,
  instagram: SvgInstagram,
  italic: SvgItalic,
  key: SvgKey,
  layers: SvgLayers,
  layout: SvgLayout,
  'life-buoy': SvgLifeBuoy,
  'link-2': SvgLink2,
  link: SvgLink,
  linkedin: SvgLinkedin,
  list: SvgList,
  loader: SvgLoader,
  lock: SvgLock,
  'log-in': SvgLogIn,
  'log-out': SvgLogOut,
  mail: SvgMail,
  'map-pin': SvgMapPin,
  map: SvgMap,
  'maximize-2': SvgMaximize2,
  maximize: SvgMaximize,
  meh: SvgMeh,
  menu: SvgMenu,
  'message-circle': SvgMessageCircle,
  'message-square': SvgMessageSquare,
  'mic-off': SvgMicOff,
  mic: SvgMic,
  'minimize-2': SvgMinimize2,
  minimize: SvgMinimize,
  'minus-circle': SvgMinusCircle,
  'minus-square': SvgMinusSquare,
  minus: SvgMinus,
  monitor: SvgMonitor,
  moon: SvgMoon,
  'more-horizontal': SvgMoreHorizontal,
  'more-vertical': SvgMoreVertical,
  'mouse-pointer': SvgMousePointer,
  move: SvgMove,
  music: SvgMusic,
  'navigation-2': SvgNavigation2,
  navigation: SvgNavigation,
  octagon: SvgOctagon,
  package: SvgPackage,
  paperclip: SvgPaperclip,
  'pause-circle': SvgPauseCircle,
  pause: SvgPause,
  'pen-tool': SvgPenTool,
  percent: SvgPercent,
  'phone-call': SvgPhoneCall,
  'phone-forwarded': SvgPhoneForwarded,
  'phone-incoming': SvgPhoneIncoming,
  'phone-missed': SvgPhoneMissed,
  'phone-off': SvgPhoneOff,
  'phone-outgoing': SvgPhoneOutgoing,
  phone: SvgPhone,
  'pie-chart': SvgPieChart,
  'play-circle': SvgPlayCircle,
  play: SvgPlay,
  'plus-circle': SvgPlusCircle,
  'plus-square': SvgPlusSquare,
  plus: SvgPlus,
  pocket: SvgPocket,
  power: SvgPower,
  printer: SvgPrinter,
  radio: SvgRadio,
  'refresh-ccw': SvgRefreshCcw,
  'refresh-cw': SvgRefreshCw,
  repeat: SvgRepeat,
  rewind: SvgRewind,
  'rotate-ccw': SvgRotateCcw,
  'rotate-cw': SvgRotateCw,
  rss: SvgRss,
  save: SvgSave,
  scissors: SvgScissors,
  search: SvgSearch,
  send: SvgSend,
  server: SvgServer,
  settings: SvgSettings,
  'share-2': SvgShare2,
  share: SvgShare,
  'shield-off': SvgShieldOff,
  shield: SvgShield,
  'shopping-bag': SvgShoppingBag,
  'shopping-cart': SvgShoppingCart,
  shuffle: SvgShuffle,
  sidebar: SvgSidebar,
  'skip-back': SvgSkipBack,
  'skip-forward': SvgSkipForward,
  slack: SvgSlack,
  slash: SvgSlash,
  sliders: SvgSliders,
  smartphone: SvgSmartphone,
  smile: SvgSmile,
  speaker: SvgSpeaker,
  square: SvgSquare,
  star: SvgStar,
  'stop-circle': SvgStopCircle,
  sun: SvgSun,
  sunrise: SvgSunrise,
  sunset: SvgSunset,
  tablet: SvgTablet,
  tag: SvgTag,
  target: SvgTarget,
  terminal: SvgTerminal,
  thermometer: SvgThermometer,
  'thumbs-down': SvgThumbsDown,
  'thumbs-up': SvgThumbsUp,
  'toggle-left': SvgToggleLeft,
  'toggle-right': SvgToggleRight,
  tool: SvgTool,
  'trash-2': SvgTrash2,
  trash: SvgTrash,
  trello: SvgTrello,
  'trending-down': SvgTrendingDown,
  'trending-up': SvgTrendingUp,
  triangle: SvgTriangle,
  truck: SvgTruck,
  tv: SvgTv,
  twitch: SvgTwitch,
  twitter: SvgTwitter,
  type: SvgType,
  umbrella: SvgUmbrella,
  underline: SvgUnderline,
  unlock: SvgUnlock,
  'upload-cloud': SvgUploadCloud,
  upload: SvgUpload,
  'user-check': SvgUserCheck,
  'user-minus': SvgUserMinus,
  'user-plus': SvgUserPlus,
  'user-x': SvgUserX,
  user: SvgUser,
  users: SvgUsers,
  'video-off': SvgVideoOff,
  video: SvgVideo,
  voicemail: SvgVoicemail,
  'volume-1': SvgVolume1,
  'volume-2': SvgVolume2,
  'volume-x': SvgVolumeX,
  volume: SvgVolume,
  watch: SvgWatch,
  'wifi-off': SvgWifiOff,
  wifi: SvgWifi,
  wind: SvgWind,
  'x-circle': SvgXCircle,
  'x-octagon': SvgXOctagon,
  'x-square': SvgXSquare,
  x: SvgX,
  youtube: SvgYoutube,
  'zap-off': SvgZapOff,
  zap: SvgZap,
  'zoom-in': SvgZoomIn,
  'zoom-out': SvgZoomOut,
}
