const tmp = {
  sys: {
    type: 'Array',
  },
  total: 7,
  skip: 0,
  limit: 100,
  items: [
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'allFieldTypes',
        type: 'ContentType',
        createdAt: '2020-01-23T10:32:14.872Z',
        updatedAt: '2020-01-23T23:07:09.121Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 9,
        publishedAt: '2020-01-23T23:07:09.121Z',
        firstPublishedAt: '2020-01-23T10:32:15.290Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 5,
        version: 10,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'allFieldTypes',
      description: 'All field types',
      fields: [
        {
          id: 'dateField',
          name: 'Date field',
          type: 'Date',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'dropdownField',
          name: 'Dropdown field',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              in: ['item A', 'item B', 'item C'],
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'imageField',
          name: 'Image field',
          type: 'Link',
          localized: false,
          required: false,
          validations: [
            {
              linkMimetypeGroup: ['image'],
            },
          ],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'longTextField',
          name: 'Long text field',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'multipleComponentsField',
          name: 'Multiple components field',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [
              {
                linkContentType: ['page', 'firstSection', 'secondSection'],
              },
            ],
            linkType: 'Entry',
          },
        },
        {
          id: 'numberField',
          name: 'Number field',
          type: 'Integer',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'richTextField',
          name: 'Rich text field',
          type: 'RichText',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'shortTextField',
          name: 'Short text field',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              size: {
                max: 155,
                min: 0,
              },
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'shortTextFieldExtended',
          name: 'Short text field extended',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              message: 'Please use camel case: onlyCamelCaseAllowed',
              regexp: {
                pattern: '^[a-z]+([A-Z][a-z0-9]+)*$',
              },
            },
            {
              size: {
                max: 155,
                min: 0,
              },
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'singleComponentField',
          name: 'Single component field',
          type: 'Link',
          localized: false,
          required: false,
          validations: [
            {
              linkContentType: ['pageModel'],
            },
          ],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'tagsField',
          name: 'Tags field',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Symbol',
            validations: [],
          },
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'subPageModel',
        type: 'ContentType',
        createdAt: '2020-01-08T09:11:10.308Z',
        updatedAt: '2020-01-23T23:07:05.851Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 35,
        publishedAt: '2020-01-23T23:07:05.851Z',
        firstPublishedAt: '2020-01-08T09:11:10.651Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 18,
        version: 36,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'subPageModel',
      description: 'Sub page model',
      fields: [
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'secondSection',
        type: 'ContentType',
        createdAt: '2020-01-08T09:11:08.338Z',
        updatedAt: '2020-01-23T23:07:03.275Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 35,
        publishedAt: '2020-01-23T23:07:03.275Z',
        firstPublishedAt: '2020-01-08T09:11:08.908Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 18,
        version: 36,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'secondSection',
      description: 'Second section',
      fields: [
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'pageModel',
        type: 'ContentType',
        createdAt: '2020-01-08T09:11:06.447Z',
        updatedAt: '2020-01-23T23:07:00.211Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 35,
        publishedAt: '2020-01-23T23:07:00.211Z',
        firstPublishedAt: '2020-01-08T09:11:06.778Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 18,
        version: 36,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'pageModel',
      description: 'Page model',
      fields: [
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'noFragment',
        type: 'ContentType',
        createdAt: '2020-01-08T09:11:04.530Z',
        updatedAt: '2020-01-23T23:06:57.442Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 35,
        publishedAt: '2020-01-23T23:06:57.442Z',
        firstPublishedAt: '2020-01-08T09:11:04.922Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 18,
        version: 36,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'noFragment',
      description: 'No fragment',
      fields: [
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'globalModel',
        type: 'ContentType',
        createdAt: '2020-01-08T09:11:02.108Z',
        updatedAt: '2020-01-23T23:06:54.201Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 36,
        publishedAt: '2020-01-23T23:06:54.201Z',
        firstPublishedAt: '2020-01-08T09:11:02.456Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 18,
        version: 37,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'globalModel',
      description: 'Global model',
      fields: [
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: {
            type: 'Link',
            linkType: 'Space',
            id: 'm2mavaumd3gp',
          },
        },
        id: 'firstSection',
        type: 'ContentType',
        createdAt: '2020-01-08T09:10:59.964Z',
        updatedAt: '2020-01-23T23:06:51.103Z',
        environment: {
          sys: {
            id: 'master',
            type: 'Link',
            linkType: 'Environment',
          },
        },
        publishedVersion: 37,
        publishedAt: '2020-01-23T23:06:51.103Z',
        firstPublishedAt: '2020-01-08T09:11:00.419Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
        publishedCounter: 19,
        version: 38,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '0KkjZqgmBqanNQA4MN9iA5',
          },
        },
      },
      displayField: 'title',
      name: 'firstSection',
      description: 'First section',
      fields: [
        {
          id: 'defaultField',
          name: 'Default field',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
  ],
}
