import { WheelroomFields } from './wheelroom-fields'

export interface WheelroomComponents {
  [componentName: string]: WheelroomComponent
}

export type CreatePageQuery = 'page' | 'global' | 'subPage'

export interface GraphQL {
  // TODO: Implement this in plugin
  /** When set boilerplate code can be generated by a plugin */
  boilerplate?: boolean
  /** When set the model is retreived when generating a static version of the site */
  createPageQuery?: CreatePageQuery
  /** When set fragment files can be generated by a plugin */
  fragment?: boolean
  /** The query is limited to the numer of items set here */
  limit?: number
  /** When set, the model is listed as a page section when editing pages */
  pageSection?: boolean
}

export interface WheelroomComponent {
  /** Fields for this component */
  fields: WheelroomFields
  /** Defines which queries are generated */
  graphQL: GraphQL
  /** Used for comparing Contentful model version with repository model version  */
  modelVersion: string
}
