import { Components } from '../../types/components'
export const expectComponents: Components = {
  article: {
    fields: {
      articleText: {
        fieldType: 'richText',
        helpText: 'Article text for article',
        initialContent: 'Demo content for article article text',
        localized: false,
        required: false,
      },
      author: {
        fieldType: 'shortText',
        helpText: 'Author for article',
        initialContent: 'Demo content for article author',
        localized: false,
        required: true,
      },
      createdAt: {
        fieldType: 'date',
        helpText: 'Created at for article',
        initialContent: 'Demo content for article created at',
        localized: false,
        required: false,
        systemField: true,
      },
      date: {
        fieldType: 'date',
        helpText: 'Date for article',
        initialContent: 'Demo content for article date',
        localized: false,
        required: true,
      },
      heading: {
        fieldType: 'shortText',
        helpText: 'Heading for article',
        initialContent: 'Demo content for article heading',
        localized: false,
        required: true,
      },
      image: {
        fieldType: 'image',
        helpText: 'Image for article',
        initialContent: 'Demo content for article image',
        localized: false,
        required: false,
      },
      slug: {
        fieldType: 'shortText',
        helpText: 'Slug for article',
        initialContent: 'demo-slug-article',
        localized: false,
        required: true,
        unique: true,
      },
      subHeading: {
        fieldType: 'shortText',
        helpText: 'Sub heading for article',
        initialContent: 'Demo content for article sub heading',
        localized: false,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for article title',
        localized: false,
        required: true,
      },
      updatedAt: {
        fieldType: 'date',
        helpText: 'Updated at for article',
        initialContent: 'Demo content for article updated at',
        localized: false,
        required: false,
        systemField: true,
      },
    },
    graphQL: {
      createPageQuery: 'subPage',
      fragment: true,
      limit: 10,
    },
    modelVersion: '1.0.0',
  },
  articleSection: {
    fields: {
      articleText: {
        fieldType: 'shortText',
        helpText: 'Article text for article section',
        initialContent: 'Demo content for article section article text',
        localized: true,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for article section title',
        localized: false,
        required: true,
      },
      variation: {
        fieldType: 'dropdown',
        helpText: 'Select a variation',
        initialContent: 'Demo content for article section variation',
        items: [
          'Inline article text, specific to this section',
          'Linked article text, derived from slug in url',
        ],
        localized: false,
        required: true,
      },
    },
    graphQL: {
      fragment: true,
      pageSection: true,
    },
    modelVersion: '1.0.0',
  },
  articlesSection: {
    fields: {
      articles: {
        components: ['article'],
        fieldType: 'multipleComponents',
        helpText: 'Articles for articles section',
        initialContent: 'Demo content for articles section articles',
        localized: false,
        required: false,
      },
      heading: {
        fieldType: 'shortText',
        helpText: 'Heading for articles section',
        initialContent: 'Demo content for articles section heading',
        localized: false,
        required: false,
      },
      maxArticles: {
        fieldType: 'number',
        helpText: 'Max articles for articles section',
        initialContent: 5,
        localized: false,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for articles section title',
        localized: false,
        required: true,
      },
    },
    graphQL: {
      fragment: true,
      pageSection: true,
    },
    modelVersion: '1.0.0',
  },
  exampleBlock: {
    fields: {
      someText: {
        fieldType: 'shortText',
        helpText: 'Some text for example block',
        initialContent: 'Demo content for example block some text',
        localized: false,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for example block title',
        localized: false,
        required: true,
      },
    },
    graphQL: {
      fragment: false,
      pageSection: false,
    },
    modelVersion: '1.0.0',
  },
  examplePart: {
    fields: {
      someText: {
        fieldType: 'shortText',
        helpText: 'Some text for example part',
        initialContent: 'Demo content for example part some text',
        localized: false,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for example part title',
        localized: false,
        required: true,
      },
    },
    graphQL: {
      fragment: true,
      pageSection: false,
    },
    modelVersion: '1.0.0',
  },
  globals: {
    fields: {
      addressLine1: {
        fieldType: 'shortText',
        helpText: 'Address line1 for globals',
        initialContent: 'Demo content for globals address line1',
        localized: false,
        required: true,
      },
      addressLine2: {
        fieldType: 'shortText',
        helpText: 'Address line2 for globals',
        initialContent: 'Demo content for globals address line2',
        localized: false,
        required: true,
      },
      emailAddress: {
        fieldType: 'shortText',
        helpText: 'Email address for globals',
        initialContent: 'Demo content for globals email address',
        localized: false,
        required: true,
      },
      githubUrl: {
        fieldType: 'shortText',
        helpText: 'Github url for globals',
        initialContent: 'Demo content for globals github url',
        localized: false,
        required: false,
      },
      heading: {
        fieldType: 'shortText',
        helpText: 'Heading for globals',
        initialContent: 'Demo content for globals heading',
        localized: false,
        required: true,
      },
      linkedinUrl: {
        fieldType: 'shortText',
        helpText: 'Linkedin url for globals',
        initialContent: 'Demo content for globals linkedin url',
        localized: false,
        required: false,
      },
      phoneNumber: {
        fieldType: 'shortText',
        helpText: 'Phone number for globals',
        initialContent: 'Demo content for globals phone number',
        localized: false,
        required: false,
      },
      siteAuthor: {
        fieldType: 'shortText',
        helpText: 'Site author for globals',
        initialContent: 'Demo content for globals site author',
        localized: false,
        required: false,
      },
      siteDescription: {
        fieldType: 'shortText',
        helpText: 'Site description for globals',
        initialContent: 'Demo content for globals site description',
        localized: false,
        required: false,
      },
      siteKeywords: {
        fieldType: 'tags',
        helpText: 'Site keywords for globals',
        initialContent: 'Demo content for globals site keywords',
        localized: false,
        required: false,
      },
      siteTitle: {
        fieldType: 'shortText',
        helpText: 'Site title for globals',
        initialContent: 'Demo content for globals site title',
        localized: false,
        required: false,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for globals title',
        localized: false,
        required: true,
      },
    },
    graphQL: {
      createPageQuery: 'global',
      fragment: true,
    },
    modelVersion: '1.0.0',
  },
  page: {
    fields: {
      image: {
        fieldType: 'image',
        helpText: 'Image for page',
        initialContent: 'Demo content for page image',
        localized: false,
        required: false,
      },
      navigationTitle: {
        fieldType: 'shortText',
        helpText: 'Navigation title for page',
        initialContent: 'Demo content for page navigation title',
        localized: false,
        required: true,
      },
      sections: {
        components: ['articleSection', 'articlesSection'],
        fieldType: 'multipleComponents',
        helpText: 'Select sections for this page',
        initialContent: 'Demo content for page sections',
        localized: false,
        required: true,
      },
      seoDescription: {
        fieldType: 'shortText',
        helpText: 'Seo description for page',
        initialContent: 'Demo content for page seo description',
        localized: false,
        maxLength: 155,
        required: true,
      },
      seoTitle: {
        fieldType: 'shortText',
        helpText: 'Seo title for page',
        initialContent: 'Demo content for page seo title',
        localized: false,
        required: true,
      },
      title: {
        fieldType: 'shortText',
        helpText: 'Never displayed, only used for listing within Contentful',
        initialContent: 'Demo content for page title',
        localized: false,
        required: true,
      },
    },
    graphQL: {
      createPageQuery: 'page',
      fragment: true,
    },
    modelVersion: '1.0.0',
  },
}
