import { StyledSystemConfig } from './types'

export const styledSystemConfig: StyledSystemConfig = {
  ignoreProperties: ['children'],
  propertyAliases: {
    bg: ['backgroundColor'],
    h: ['height'],
    m: ['marginTop', 'marginRight', 'marginBottom', 'marginLeft'],
    margin: ['marginTop', 'marginRight', 'marginBottom', 'marginLeft'],
    mb: ['marginBottom'],
    ml: ['marginLeft'],
    mr: ['marginRight'],
    mt: ['marginTop'],
    mx: ['marginRight', 'marginLeft'],
    my: ['marginTop', 'marginBottom'],
    p: ['paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft'],
    padding: ['paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft'],
    pb: ['paddingBottom'],
    pl: ['paddingLeft'],
    pr: ['paddingRight'],
    pt: ['paddingTop'],
    px: ['paddingRight', 'paddingLeft'],
    py: ['paddingTop', 'paddingBottom'],
    w: ['width'],
  },
  responsiveProperties: [
    'alignItems',
    'backgroundColor',
    'borderBottom',
    'borderLeft',
    'borderRadius',
    'borderRight',
    'borderTop',
    'bottom',
    'color',
    'display',
    'flexDirection',
    'fontSize',
    'fontWeight',
    'height',
    'justifyContent',
    'left',
    'lineHeight',
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginTop',
    'opacity',
    'order',
    'paddingBottom',
    'paddingLeft',
    'paddingRight',
    'paddingTop',
    'right',
    'top',
    'textAlign',
    'visibility',
    'width',
    'maxWidth',
  ],
  scales: {
    fontSizeScale: ['fontSize'],
    fontWeightScale: ['fontWeight'],
    lineHeightScale: ['lineHeight'],
    spaceScale: [
      'bottom',
      'left',
      'marginBottom',
      'marginLeft',
      'marginRight',
      'marginTop',
      'paddingBottom',
      'paddingLeft',
      'paddingRight',
      'paddingTop',
      'right',
      'top',
    ],
  },
  initialZeroScales: ['fontSizeScale', 'fontWeightScale', 'lineHeightScale'],
  stringMaps: {
    colorMap: [
      'backgroundColor',
      'borderBottomColor',
      'borderColor',
      'borderLeftColor',
      'borderRightColor',
      'borderTopColor',
      'caretColor',
      'color',
      'fill',
      'columnRuleColor',
      'outlineColor',
      'textDecorationColor',
    ],
    fontMap: ['fontFamily'],
  },
  units: {
    percent: [
      'bottom',
      'left',
      'right',
      'top',
      'height',
      'width',
      'maxWidth',
      'minWidth',
      'maxHeight',
      'minHeight',
    ],
    px: [
      'fontSize',
      'marginBottom',
      'marginLeft',
      'marginRight',
      'marginTop',
      'paddingBottom',
      'paddingLeft',
      'paddingRight',
      'paddingTop',
    ],
  },
}
