/**
 *
 *  Common fields are present in all models
 *
 */

import { WheelroomFields } from '@jacco-meijer/wheelroom'
import { ShortTextField } from '@jacco-meijer/wheelroom'

export const configCommonFields: WheelroomFields = {
  __typename: {
    system: true,
    type: 'shortText',
  } as ShortTextField,
  title: {
    helpText: 'Only used within Contentful, does not appear on the site itself',
    initialContent: '%Component name% generated by boilerplate',
    name: 'Title within Contentful',
    required: true,
    type: 'shortText',
  } as ShortTextField,
}
